"""Add foreign keys to TeacherRating

Revision ID: 16ccbe7d9365
Revises: 83cda156fc77
Create Date: 2024-06-23 22:04:49.440197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ccbe7d9365'
down_revision: Union[str, None] = '83cda156fc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
